from util import *

def test_case_task(test_task, test_request, codegen_query):

    codegen_query = populate_task_query(codegen_query)

    query = """Your task is to generate executable test cases for the code generated by LLM.
    The python3 code was generated by the following prompt:

    ###
        {codegen_query}
    ###

    The generated code is in {code_path}, it can be called by subprocess.run(['python3', code_path]).
    
    {test_request}

    Your test cases should be complete and the dataset should be consistent.
    Your code should include the setup and be executable by itself.
    """

    template = """You are a helpful QA agent"""

    code_path = test_task.replace(' ', '_')+".py"

    query = query.format(code_path=code_path, codegen_query=codegen_query, test_request=test_request)

    run_task(test_task+" test cases", template, query, T_CODE)